#!/bin/bash

echo "╔═══════════════════════════════════════════════════════════════════╗"
echo "║                   CalDAV Migration Tool                           ║"
echo "║                Complete Project Structure                         ║"
echo "╚═══════════════════════════════════════════════════════════════════╝"
echo ""
echo "📁 caldav-migration/"
echo "│"
echo "├── 🌐 WEB APPLICATION"
echo "│   ├── app.py                    # Flask REST API server"
echo "│   ├── models.py                 # SQLAlchemy database models"
echo "│   ├── worker.py                 # Background job processor"
echo "│   ├── templates/"
echo "│   │   └── index.html           # Main web interface"
echo "│   └── static/"
echo "│       ├── app.js               # Frontend JavaScript"
echo "│       └── style.css            # Custom styling"
echo "│"
echo "├── 🔧 CORE ENGINE"
echo "│   ├── caldav_client.py         # CalDAV/CardDAV client wrapper"
echo "│   └── migration.py             # Migration logic engine"
echo "│"
echo "├── 💻 CLI TOOL"
echo "│   └── migrate.py               # Command-line interface"
echo "│"
echo "├── 📦 CONFIGURATION"
echo "│   ├── requirements.txt         # Python deps (CLI)"
echo "│   ├── requirements-web.txt     # Python deps (Web)"
echo "│   ├── config.example.json      # Example CLI config"
echo "│   ├── start-web.sh            # Web startup script"
echo "│   └── .gitignore              # Git ignore rules"
echo "│"
echo "├── 📚 DOCUMENTATION"
echo "│   ├── INDEX.md                 # Documentation index (start here!)"
echo "│   ├── README.md                # Main documentation"
echo "│   ├── SUMMARY.md               # Complete overview"
echo "│   ├── WEB_README.md           # Web interface guide"
echo "│   ├── EXAMPLES.md             # Usage examples"
echo "│   ├── STRUCTURE.md            # Architecture details"
echo "│   ├── UI_GUIDE.md             # Visual interface guide"
echo "│   └── PROJECT_TREE.sh         # This file"
echo "│"
echo "└── 💾 RUNTIME DATA (generated)"
echo "    └── caldav_migration.db     # SQLite database"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "📊 PROJECT STATISTICS"
echo "───────────────────────────────────────────────────────────────────"

# Count files by type
py_files=$(find . -name "*.py" -not -path "./venv/*" | wc -l)
md_files=$(find . -name "*.md" | wc -l)
html_files=$(find . -name "*.html" | wc -l)
js_files=$(find . -name "*.js" | wc -l)
css_files=$(find . -name "*.css" | wc -l)
total_files=$(find . -type f -not -path './venv/*' -not -path './.git/*' -not -name '*.pyc' -not -name '*.db' | wc -l)

echo "Python files:         $py_files"
echo "Documentation files:  $md_files"
echo "HTML templates:       $html_files"
echo "JavaScript files:     $js_files"
echo "CSS files:            $css_files"
echo "───────────────────────────────────────────────────────────────────"
echo "Total project files:  $total_files"
echo ""

# Count lines of code
if command -v cloc &> /dev/null; then
    echo "═══════════════════════════════════════════════════════════════════"
    echo "📝 CODE STATISTICS (via cloc)"
    echo "═══════════════════════════════════════════════════════════════════"
    cloc --quiet --exclude-dir=venv,.git . 2>/dev/null || echo "Unable to generate code statistics"
else
    echo "💡 Install 'cloc' for detailed code statistics: sudo apt install cloc"
fi

echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "🚀 QUICK START"
echo "═══════════════════════════════════════════════════════════════════"
echo ""
echo "Web Interface (Recommended):"
echo "  ./start-web.sh"
echo "  Then open: http://localhost:5000"
echo ""
echo "Command Line:"
echo "  cp config.example.json config.json"
echo "  # Edit config.json with your credentials"
echo "  ./migrate.py --config config.json --dry-run"
echo ""
echo "Documentation:"
echo "  cat INDEX.md        # Documentation index"
echo "  cat SUMMARY.md      # Project overview"
echo "  cat EXAMPLES.md     # Usage examples"
echo ""
echo "═══════════════════════════════════════════════════════════════════"
echo "✨ All files are in place and ready to use!"
echo "═══════════════════════════════════════════════════════════════════"
